apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-12-18T04:42:30Z"
  labels:
    app: grafana
    chart: grafana
    heritage: Tiller
    release: istio
    hpecp.hpe.com/hpecp-internal-gateway: "true"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:app: {}
          f:chart: {}
          f:heritage: {}
          f:release: {}
      f:spec:
        f:ports:
          .: {}
          k:{"port":3000,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: kubectl
    operation: Update
    time: "2020-12-18T04:42:30Z"
  name: grafana
  namespace: istio-system
  resourceVersion: "1616051"
  selfLink: /api/v1/namespaces/istio-system/services/grafana
  uid: c4f80af3-3104-4ffb-b478-671530c8cdec
spec:
  clusterIP: 10.110.19.84
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: grafana
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
